# Generated by Django 6.0 on 2025-12-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps location URL for the academy', null=True),
        ),
    ]
