# Generated by Django 4.2.27 on 2025-12-27 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=10)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of features included in this plan')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default plan for new registrations')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('member_type', models.CharField(choices=[('student', 'Student'), ('adult', 'Adult'), ('parent_child', 'Parent registering for Child')], default='student', max_length=20)),
                ('is_child_registration', models.BooleanField(default=False)),
                ('parent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Consent to terms and conditions')),
                ('privacy_accepted', models.BooleanField(default=False, help_text='Privacy policy accepted')),
                ('newsletter_subscription', models.BooleanField(default=False, help_text='Subscribe to newsletters')),
                ('registration_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active Member'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('membership_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL)),
                ('membership_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.membershipplan')),
            ],
            options={
                'verbose_name': 'Club Membership',
                'verbose_name_plural': 'Club Memberships',
                'ordering': ['-registration_date'],
            },
        ),
    ]
