# Generated by Django 4.2.27 on 2025-12-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_membershipplan_clubmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, help_text='Additional message or questions')),
                ('subscribed_to_newsletter', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Enrollment',
                'verbose_name_plural': 'Service Enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
