# Generated by Django 4.2.27 on 2025-12-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Member bio or background')),
                ('role', models.CharField(blank=True, help_text='Role or position', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.RemoveField(
            model_name='serviceinquiry',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
        migrations.DeleteModel(
            name='ServiceInquiry',
        ),
    ]
