# Generated by Django 4.2.27 on 2025-12-27 17:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(choices=[('online_lichess', 'Online (Lichess)'), ('online_chesscom', 'Online (Chess.com)'), ('physical', 'Physical Venue'), ('hybrid', 'Hybrid (Online & Physical)')], default='online_lichess', max_length=50)),
                ('venue_details', models.TextField(blank=True, help_text='Physical address or additional location info')),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('swiss', 'Swiss System'), ('knockout', 'Knockout'), ('arena', 'Arena')], default='swiss', max_length=20)),
                ('time_control', models.CharField(default='10+0', help_text='E.g., 10+0, 5+3, 15+10', max_length=50)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('lichess_link', models.URLField(blank=True, help_text='Lichess tournament link for users to join directly')),
                ('results_link', models.URLField(blank=True, help_text='Link to tournament results/standings')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_registration', models.BooleanField(default=True, help_text='If False, users click Lichess link directly without registering')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('lichess_username', models.CharField(blank=True, help_text='Optional Lichess username', max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, help_text='Chess rating (optional)', null=True)),
                ('message', models.TextField(blank=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['registered_at'],
                'unique_together': {('tournament', 'email')},
            },
        ),
    ]
